apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCound }}
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rolliingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: python-helloworld
              